
# CM-903: Prevent ntpd from exiting if clock is way off
tinker panic 0

# general configuration parameters
driftfile /var/lib/ntp/ntp.drift


# make certain that we don't ever use something other than an approved
# timeserver for synchronization
restrict default nomodify
restrict 212.138.72.41 nomodify noquery notrap nopeer
restrict 194.186.237.38 nomodify noquery notrap nopeer
restrict 103.123.108.224 nomodify noquery notrap nopeer
restrict 162.159.200.123 nomodify noquery notrap nopeer

restrict 17.253.116.253 nomodify noquery notrap nopeer
restrict 210.243.152.152 nomodify noquery notrap nopeer
restrict 111.235.248.121 nomodify noquery notrap nopeer
restrict 162.159.200.123 nomodify noquery notrap nopeer

# Our time servers, selected from ../../common/ntp/ntp_servers.db in the [*.*] section
# Asia pool zones
server 212.138.72.41
server 194.186.237.38
server 103.123.108.224
server 162.159.200.123
# pool.ntp.org zones
server 17.253.116.253
server 210.243.152.152
server 111.235.248.121
server 162.159.200.123
