#!/bin/sh
#
# Copyright (c) 2016, The Linux Foundation. All rights reserved.
#
# Permission to use, copy, modify, and/or distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
#

default_uboot_env () {
	UBOOTENV_PART=$(cat /proc/mtd | grep APPSBLENV)
	mtd_dev=$(echo $UBOOTENV_PART | awk '{print $1}' | sed 's/:$//')
	mtd_size=0x$(echo $UBOOTENV_PART | awk '{print $2}')
	mtd_erase=0x$(echo $UBOOTENV_PART | awk '{print $3}')
	nor_flash=`find /sys/bus/spi/devices/*/mtd -name ${mtd_dev}`

	if [ -z "$UBOOTENV_PART" ]; then
		mtd_dev=$(echo $(find_mmc_part "0:APPSBLENV") | sed 's/^.\{5\}//')
		if [ -n "$mtd_dev" ]; then
			EMMC_UBOOTENV_PART=$(cat /proc/partitions | grep $mtd_dev)
			#convert block to bytes
			emmc_uboot_env_size=`expr $(echo $EMMC_UBOOTENV_PART | awk '{print $3}') \* 1024`
			uboot_env_size=0x`printf "%x" $emmc_uboot_env_size`
		fi
		mtd_erase=""
	elif [ -n "$nor_flash" ]; then
		uboot_env_size=$mtd_size
		# mtd_erase=""
	else
		# size is hardcoded to 0x40000 in u-boot
		uboot_env_size=0x40000
		# sectors=$(( $uboot_env_size / $mtd_erase ))
	fi
	sectors=$(( $uboot_env_size / $mtd_erase ))
	echo "/dev/$mtd_dev 0x0 $uboot_env_size $mtd_erase 0x$sectors" > /etc/fw_env.config
}

default_uboot_env

exit 0
